import gmsh, numpy as np
gmsh.initialize()
gmsh.option.setNumber("General.Terminal", 0)
gmsh.model.add("c")
gmsh.model.occ.importShapes(r"E:\Projects\Federica\federica_scaffold.step")
gmsh.model.occ.synchronize()
gmsh.option.setNumber("Mesh.MeshSizeMin", 0.08)
gmsh.option.setNumber("Mesh.MeshSizeMax", 0.20)
gmsh.model.mesh.generate(2)
_, coord, _ = gmsh.model.mesh.getNodes()
c = np.array(coord).reshape(-1,3)
print("true node bbox min:", np.round(c.min(0),4))
print("true node bbox max:", np.round(c.max(0),4))
gmsh.finalize()
